### ISSUE TITLE
The latest tmux has deprecated `-p` option for split-window

### ISSUE THREAD

**Issue by liangkarl** [evnp/tmux-run#7]
As title, it seems like `-p` is replaced by `-l`, so the tmex would fail to create new panes
```bash
$ tmux -V
tmux next-3.4
$ tmux split-window -p 34
size missing
```

**Comment by evnp** [comment]
Thanks for the heads up @liangkarl. Unless I'm missing something, looks like we'll have to support both old and new versions with this change – otherwise we'd need specific versions of tmex compatible with corresponding versions of tmux, which seems nightmarish.. open to your thoughts on that though.

I put up https://github.com/evnp/tmex/pull/8 to address this, will merge and publish it tomorrow unless you have any feedback.

**Comment by evnp** [comment]
https://github.com/evnp/tmex/releases/tag/v1.0.10 is available now, which should resolve this. Please let me know if you have any issues with it (feel free to reopen this).

**Comment by liangkarl** [comment]
Thanks a lot!
